<?php
__( 'Dashboard', 'wishlist-member' );
__( 'Setup', 'wishlist-member' );
__( 'Levels', 'wishlist-member' );
__( 'Pay Per Posts', 'wishlist-member' );
__( 'Settings', 'wishlist-member' );
__( 'Integrations', 'wishlist-member' );
__( 'Payment Providers', 'wishlist-member' );
__( 'Email Providers', 'wishlist-member' );
__( 'Other Services', 'wishlist-member' );
__( 'Getting Started', 'wishlist-member' );
__( 'Members', 'wishlist-member' );
__( 'Manage', 'wishlist-member' );
__( 'Import', 'wishlist-member' );
__( 'Export', 'wishlist-member' );
__( 'Mass Move/Add', 'wishlist-member' );
__( 'Sequential Upgrade', 'wishlist-member' );
__( 'Blacklist', 'wishlist-member' );
__( 'Data Privacy', 'wishlist-member' );
__( 'Email Templates', 'wishlist-member' );
__( 'Manage User Data', 'wishlist-member' );
__( 'Administration', 'wishlist-member' );
__( 'Email Broadcasts', 'wishlist-member' );
__( 'Backup', 'wishlist-member' );
__( 'Site Migration', 'wishlist-member' );
__( 'Export Settings', 'wishlist-member' );
__( 'Import Settings', 'wishlist-member' );
__( 'Reset Settings', 'wishlist-member' );
__( 'Version Rollback', 'wishlist-member' );
__( 'Content Protection', 'wishlist-member' );
__( 'Posts', 'wishlist-member' );
__( 'Content', 'wishlist-member' );
__( 'Comments', 'wishlist-member' );
__( 'Pages', 'wishlist-member' );
__( 'Categories', 'wishlist-member' );
__( 'Folders', 'wishlist-member' );
__( 'Files', 'wishlist-member' );
__( 'Content Control', 'wishlist-member' );
__( 'Advanced Options', 'wishlist-member' );
__( 'Global Defaults', 'wishlist-member' );
__( 'Admin Info', 'wishlist-member' );
__( 'Error Pages', 'wishlist-member' );
__( 'Redirects', 'wishlist-member' );
__( 'Protection', 'wishlist-member' );
__( 'Email', 'wishlist-member' );
__( 'Other', 'wishlist-member' );
__( 'Logins', 'wishlist-member' );
__( 'Styling', 'wishlist-member' );
__( 'Passwords', 'wishlist-member' );
__( 'Privileges', 'wishlist-member' );
__( 'Caching', 'wishlist-member' );
__( 'Miscellaneous', 'wishlist-member' );
__( 'Registrations', 'wishlist-member' );
__( 'Custom Forms', 'wishlist-member' );
__( 'Registration Settings', 'wishlist-member' );
__( 'Legacy', 'wishlist-member' );
__( 'RSS', 'wishlist-member' );
__( 'Cron Jobs', 'wishlist-member' );
__( 'CSS', 'wishlist-member' );
__( 'API', 'wishlist-member' );
__( 'System Info', 'wishlist-member' );
